# Travis CI config for https://travis-ci.org/thereal1024/ProveBit
language: java
jdk: oraclejdk8

env:
  - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start
  
script:
  - cd provebit-parent
  - mvn test
